content/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/<int:id>', views.menu, name='menu'),
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('error',views.error, name='error')
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),

]

images/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment')
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),

]

project2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('images/', include('images.urls')),
    path('user/',include('user.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('error/', views.error, name='error'),
    path('category/<int:id>/<slug:slug>/', views.category_images, name='category_images'),
    path('images/<int:id>/<slug:slug>/', views.images_detail, name='images_detail'),
    path('search/', views.images_search, name='images_search'),
    path('search_auto/', views.search_auto, name="search_auto"),
    path('logout/', views.logout_view, name="logout_view"),
    path('login/', views.login_view, name="login_view"),
    path('signup/', views.signup_view, name="signup_view"),
    path('sss/', views.faq, name='faq'),
    path('content/', include('content.urls')),
    path('menu/<int:id>', views.menu, name='menu'),
    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
]
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/models.py
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Select, FileInput
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

from images.models import Category


class Menu(MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    title = models.CharField(max_length=150, unique=True)
    link = models.CharField(max_length=100, blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):  # __str__ method elaborated later in
        full_path = [self.title]  # post.  use __unicode__ in place of
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])


class Content(models.Model):
    TYPE = (
        ('menu', 'menu'),
        ('resim', 'resim'),
        ('duyuru', 'duyuru'),
        ('haber', 'haber'),
    )

    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    menu = models.OneToOneField(Menu, null=True, blank=True, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=TYPE)
    title = models.CharField(max_length=150)
    description = models.CharField(max_length=255)
    keywords = models.CharField(max_length=255)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(null=False, unique=True)
    detail = RichTextUploadingField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('content_detail', kwargs={'slug': self.slug})
class ContentForm(ModelForm):
    class Meta:
        model = Content
        fields = ['menu', 'type','title', 'slug', 'keywords', 'description', 'image', 'detail']
        widgets = {
            'title': TextInput(attrs={'class': 'input', 'placeholder': 'title'}),
            'slug': TextInput(attrs={'class': 'input', 'placeholder': 'slug'}),
            'keywords': TextInput(attrs={'class': 'input', 'placeholder': 'keywords'}),
            'description': TextInput(attrs={'class': 'input', 'placeholder': 'description'}),
            'category': Select(attrs={'class': 'input', 'placeholder': 'city'}, choices=Category.objects.all()),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
            'detail': CKEditorWidget(),
        }

class CImages(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

class CImageForm(ModelForm):
    class Meta:
        model = CImages
        fields = ['title', 'image']

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = {
        ('True', 'Evet'),
        ('False', 'Hayır')
    }
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = {
        ('True', 'New'),
        ('False', 'Read'),
        ('Closed', 'Closed')
    }
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='new')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeholder': 'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'message': Textarea(attrs={'class': 'input', 'placeholder': 'Your Message', 'rows': '5'}),
        }

class UserProfile(models.Model):
    user =models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=20)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name +' '+self.user.first_name+'[' +self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_decription = 'Image'

class UserProfileFormu(ModelForm):
    class Meta:
        model=UserProfile
        fields=['phone','address','city','country','image']

class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernumber = models.IntegerField()
    question= models.CharField(max_length=150)
    answer=models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

images/models.py
from tokenize import Comment

from ckeditor.widgets import CKEditorWidget
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Select, FileInput
from django.urls import reverse
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    STATUS = {
        ('True', 'Evet'),
        ('False', 'Hayır')
    }
    title = models.CharField(max_length=30)
    keywords = models.CharField(blank=True, max_length=255)
    description = models.CharField(blank=True, max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)

    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']

    def __str__(self):
        cat = [self.title]
        prnt = self.parent
        while prnt is not None:
            cat.append(prnt.title)
            prnt = prnt.parent
        return ' / '.join(cat[::-1])

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'


def get_absolute_url(self):
    return reverse('category_detail', kwargs={'slug': self.slug})


class Images(models.Model):
    STATUS = {
        ('True', 'Evet'),
        ('False', 'Hayır')
    }


    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)  # relation with Category table
    title = models.CharField(max_length=150)
    keywords = models.CharField(blank=True, max_length=255)
    description = models.CharField(blank=True, max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    detail = RichTextUploadingField()
    slug = models.SlugField(null=False, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class ImagesForm(ModelForm):
    class Meta:
        model = Images
        fields = ['category', 'title', 'description' ,'image', 'detail','slug']


class Foto(models.Model):
    images = models.ForeignKey(Images, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True)
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

class FotoForm(ModelForm):
    class Meta:
        model = Foto
        fields = ['title','image']

class Comment(models.Model):
    STATUS = {
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır')
    }
    image = models.ForeignKey(Images, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(max_length=200, blank=True)
    rate = models.IntegerField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default="New")
    ip = models.CharField(blank=True, max_length=20)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100, required=False)
    catid = forms.IntegerField()

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30,label="User Name :")
    email = forms.EmailField(max_length=200,label="Email :")
    first_name = forms.CharField(max_length=100,help_text="First Name",label="First Name :")
    last_name = forms.CharField(max_length=100,help_text="Last Name",label="Last Name :")

    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password1','password2',)

content/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    return HttpResponse("Content App")

images/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from images.models import CommentForm, Comment


def index(request):
    return HttpResponse("images page")


@login_required(login_url='/login')  # check login
def addcomment(request, id):
    url = request.META.get('HTTP_REFERER')  # get last url
    if request.method == 'POST':  # form post ediliyor
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user = request.user  # Access user session information

            data = Comment()  # model ile bağlantı kur
            data.user_id = current_user.id
            data.image_id = id
            data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.rate = form.cleaned_data['rate']
            data.ip = request.META.get('REMOTE_ADDR')  # client computer ip adress
            data.save()  # veritabanına kaydet

            messages.success(request, "Yorumunuz başarı ile gönderilmiştir. Teşekkür Ederiz ")

            return HttpResponseRedirect(url)
            # return HttpResponse("Kaydedildi")
        messages.warning(request, "Yorumunuz kaydedilmedi. Lütfen kontrol ediniz ")
        return HttpResponseRedirect(url)

home/templates/content_detail.html
{% extends "homebase.html" %}

{% block title %}{{ images.title }}{% endblock %}
{% block keywords %}{{ images.keywords }}{% endblock %}
{% block description %}{{ images.description }}{% endblock %}

{% block head %}
    <link rel="shortcut icon" href="{{ setting.icon.url }}">
{% endblock %}

{% block sidebar %}
    {% include "sidebar.html" %}
{% endblock %}

{% block content %}
    <section id="subintro">
        <div class="container">
            <div class="row">
                <div class="span8">
                    <ul class="breadcrumb">
                        <li><a href="/"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
                        <li><a href="/category/{{ content.category.id }}/{{ images.category.slug }}">{{images.category}}</a><i class="icon-angle-right"></i></li>
                        <li class="active">{{content.type}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section id="maincontent">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <article>
                        <div class="heading">
                            <h4>{{content.title}}</h4>
                        </div>
                        <div class="clearfix">
                        </div>
                    <div class="row">

                        <div class="tab-content">
                            <div class="tab-pane active" id="one">
                                <p>
                                    <a href="#"><img src="{{content.image.url}}"  style="height: 150px; width: 150px; float: left;" alt=""></a>
                                    {{content.detail | safe}}
                                </p>
                            </div>
                            </div>
                            <div class="row">
                                <div class="span8">
                                    <!-- start flexslider -->

                                    <div class="flexslider">

                                        <ul class="slides">
                                        <li>

                                            <img src="{{content.image.url}}" style="height: 238px; width: 620px " alt="" />
                                        </li>

                                            {% for rs in images %}
                                                <li>
                                                    <img src="{{rs.image.url}}" style="height: 238px; width: 620px " alt="" />
                                                </li>
                                            {% endfor %}
                                        </ul>

                                    </div>

                                    <!-- end flexslider -->
                                </div>
                            </div>
                        </div>
                    </article>
                    <!-- end article full post -->
                </div>
            </div>
        </div>
        <!-- end tab -->
        </div>


        </div>
    </section>
{% endblock %}

home/templates/error_page.html
{% extends "homebase.html" %}

{% block title %}ERROR-{{ setting.company }}{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}

{% block head %}
    <link rel="shortcut icon" href="{{ setting.icon.url }}">
{% endblock %}

{% block sidebar %}
    {% include "sidebar.html" %}
{% endblock %}

{% block content %}


    <!-- Subintro
   ================================================== -->
    <section id="subintro">
        <div class="container">
            <div class="row">
                <div class="span8">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
                        <li><a href="/">Anasayfa</a><i class="icon-angle-right"></i></li>
                        <li class="active">Error</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section id="maincontent">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div align="center">
                        <br><br><br><br>
                        <H1>ARADIĞINIZ İÇERİK BULUNAMADI</H1>
                        <h3><a href="/">Anasayfaya Dön</a> </h3>
                        <br><br><br><br>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

home/templates/images_detail.html
{% extends "homebase.html" %}

{% block title %}{{ images.title }}{% endblock %}
{% block keywords %}{{ images.keywords }}{% endblock %}
{% block description %}{{ images.description }}{% endblock %}

{% block head %}
    <link rel="shortcut icon" href="{{ setting.icon.url }}">
{% endblock %}

{% block sidebar %}
    {% include "sidebar.html" %}
{% endblock %}

{% block content %}
    <section id="subintro">
        <div class="container">
            <div class="row">
                <div class="span8">
                    <ul class="breadcrumb">
                        <li><a href="/"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
                        <li><a href="/category/{{ images.category.id }}/{{ images.category.slug }}">{{images.category}}</a><i class="icon-angle-right"></i></li>
                        <li class="active">{{images.title}}</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <section id="maincontent">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <article>
                        <div class="heading">
                            <h4>{{images.title}}</h4>
                        </div>
                        <div class="clearfix">
                        </div>
                        <div class="row">
                            <div class="span8">
                                <!-- start flexslider -->

                                <div class="flexslider">

                                    <ul class="slides">
                                    <li>
                                         <img src="{{images.image.url}}" style="height: 400px; width: 620px " alt="" />
                                    </li>

                                        {% for rs in fotos %}
                                            <li>
                                                <img src="{{rs.image.url}}" style="height: 400px; width: 620px " alt="" />
                                            </li>
                                        {% endfor %}
                                    </ul>

                                </div>

                                <!-- end flexslider -->
                            </div>
                            <div class="span4">
                                <aside>
                                    <div class="widget">
                                        <div class="project-widget">
                                            <h4 class="rheading">{{images.title}}<span></span></h4>
                                            <ul class="project-detail">
                                                <li><label>Project name :</label> {{images.title}}</li>
                                                <li><label>Category :</label> {{images.category}}</li>
                                                <li><label>Project detail :</label> {{images.description}}</li>
                                                <li><label>Project date :</label> {{images.create_at}}</li>
                                            </ul>
                                        </div>
                                    </div>
                                </aside>
                            </div>
                        </div>
                    </article>
                    <!-- end article full post -->
                </div>
            </div>
            <div class="span12">
                <div class="tabbable tabs-top">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#one" data-toggle="tab"> Detail</a></li>
                        <li><a href="#two" data-toggle="tab">Comments</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="one">
                            <p>
                                {{images.detail | safe}}
                            </p>
                        </div>

                        <div class="tab-pane" id="two">
                            <h4>Comments</h4>
                        {% for rs in comment %}

                            <ul class="media-list">
                                <li class="media">
                                    <a class="pull-left" href="#">
                                        <img class="media-object" src="assets/img/small-avatar.png" alt="" />
                                    </a>
                                    <div class="media-body">
                                        <h5 class="media-heading"><a href="#">{{ rs.user }}</a></h5>
                                        <span>{{rs.create_at}}</span>
                                    <b>rate : {{rs.rate}}</b>
                                    {% if rs.rate < 2 %}
                                       </b> <a class="icon-star"></a>

                                    {% elif rs.rate < 3 %}
                                       </b> <a class="icon-star"></a>
                                       </b> <a class="icon-star"></a>

                                    {% elif rs.rate < 4 %}
                                       </b> <a class="icon-star"></a>
                                       </b> <a class="icon-star"></a>
                                       </b> <a class="icon-star"></a>

                                    {% elif rs.rate < 5 %}
                                        <a class="icon-star"></a>
                                        <a class="icon-star"></a>
                                        <a class="icon-star"></a>
                                        <a class="icon-star"></a>

                                    {% elif rs.rate < 6 %}
                                        <a class="icon-star"></a>
                                        <a class="icon-star"></a>
                                        <a class="icon-star"></a>
                                        <a class="icon-star"></a>
                                        <a class="icon-star"></a>
                                    {% endif %}



                                        <br>
                                        <b>{{ rs.subject }}</b>
                                        <p>
                                            {{ rs.comment }}
                                        </p>
                                    </div>
                                </li>

                            </ul>
                        {% endfor %}
                            <div class="comment-post">
                                <h4>Leave a comment</h4>
                                {% if messages %}
                                    {% for message in messages %}
                                        <div class="alert alert-{{ message.tags }}" role="alert">
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            <p>Your email addres will not be published </p>

                                <form action="/images/addcomment/{{ images.id }}" method="post" class="comment-form" name="comment-form">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="span4">
                                            <label>Subject <span>*</span></label>
                                            <input type="text" name="subject" id="id_subject" class="input-block-level" placeholder="Subject" />
                                        </div>
                                        <div class="span4">
                                            <label>Rate <span>*</span></label>
                                            <select id="id_rate" name="rate" class="input-block-level">
                                                <option>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                        </div>
                                        <div class="span8">
                                            <label>Comment <span>*</span></label>
                                            <textarea name="comment" id="id_comment" rows="9" class="input-block-level" placeholder="Your comment"></textarea>
                                            {%  if user.id is not None %}
                                                <button class="btn btn-theme" type="submit">Submit comment</button>
                                            {% else %}
                                                Yorum eklemek için <a href="/login">login</a> olunuz!
                                            {% endif %}
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end tab -->
        </div>


        </div>
    </section>
{% endblock %}