home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('error',views.error, name='error')
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),

]

project2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('images/', include('images.urls')),
    path('user/',include('user.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('error/', views.error, name='error'),
    path('category/<int:id>/<slug:slug>/', views.category_images, name='category_images'),
    path('images/<int:id>/<slug:slug>/', views.images_detail, name='images_detail'),
    path('search/', views.images_search, name='images_search'),
    path('search_auto/', views.search_auto, name="search_auto"),
    path('logout/', views.logout_view, name="logout_view"),
    path('login/', views.login_view, name="login_view"),
    path('signup/', views.signup_view, name="signup_view"),
    path('sss/', views.faq, name='faq'),
    path('content/', include('content.urls')),
    path('menu/<int:id>', views.menu, name='menu'),
    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
]
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('imagedelete/<int:id>', views.imagedelete, name='imagedelete'),
    path('addcontent/', views.addcontent, name='addcontent'),
    path('contents/', views.contents, name='contents'),
    path('contentedit/<int:id>/', views.contentedit, name='contentedit'),
    path('contentdelete/<int:id>/', views.contentdelete, name='contentdelete'),
    path('contentaddimage/<int:id>/', views.contentaddimage, name='contentaddimage'),
    path('addfotogalery/<int:id>/', views.addfotogalery, name='addfotogalery'),
    path('fotos/', views.fotos, name='fotos'),
    path('addimage', views.addimage, name="addimage"),
    path('editimage/<int:id>', views.editimage, name="editimage"),
   # path('addcomment/<int:id>', views.addcomment, name='addcomment')
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),

]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = {
        ('True', 'Evet'),
        ('False', 'Hayır')
    }
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = {
        ('True', 'New'),
        ('False', 'Read'),
        ('Closed', 'Closed')
    }
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='new')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeholder': 'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'message': Textarea(attrs={'class': 'input', 'placeholder': 'Your Message', 'rows': '5'}),
        }

class UserProfile(models.Model):
    user =models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=20)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name +' '+self.user.first_name+'[' +self.user.username + '] '

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_decription = 'Image'

class UserProfileFormu(ModelForm):
    class Meta:
        model=UserProfile
        fields=['phone','address','city','country','image']

class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    ordernumber = models.IntegerField()
    question= models.CharField(max_length=150)
    answer=models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from content.models import Menu, Content, ContentForm, CImageForm, CImages
from home.models import UserProfile, Setting
from home.views import menu
from images.models import Category, Comment, Images, Foto, ImagesForm, FotoForm
from user.forms import UserUpdateForm, ProfileUpdateForm



def index(request):
    setting = Setting.objects.get(pk=1)
    menu = Menu.objects.all()
    category = Category.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    # return HttpResponse(profile)
    context = {
        'setting': setting,
        'menu': menu,
        'category': category,
        'profile': profile,

    }
    return render(request, 'user_profile.html', context)


@login_required(login_url='/login')
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'your account has been updated')
            return redirect('/user')
    else:
        setting = Setting.objects.get(pk=1)
        menu = Menu.objects.all()
        category = Category.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'setting': setting,
            'menu': menu,
            'category': category,
            'user_form': user_form,
            'profile_form': profile_form,

        }
        return render(request, 'user_update.html', context)


@login_required(login_url='/login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "your passwor update!")
            return HttpResponseRedirect('/user')
        else:
            messages.error(request, 'Please correct the error bellow !<br>' + str(form.errors))
            return HttpResponseRedirect('/user/password')
    else:
        setting = Setting.objects.get(pk=1)
        menu = Menu.objects.all()
        category = Category.objects.all()
        form = PasswordChangeForm(request.user)
        return render(request, 'change_password.html', {
            'form': form,
            'setting': setting,
            'menu': menu,
            'category': category

        })


@login_required(login_url='/login')
def comments(request):
    setting = Setting.objects.get(pk=1)
    menu = Menu.objects.all()
    category = Category.objects.all()
    current_user = request.user
    comments = Comment.objects.filter(user_id=current_user.id )

    context = {
        'setting': setting,
        'menu': menu,
        'category': category,
        'comments': comments,

    }
    return render(request, 'user_comments.html', context)


@login_required(login_url='/login')
def deletecomment(request, id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id, ).delete()
    messages.success(request, 'comment deleted....')
    return HttpResponseRedirect('/user/comments')


@login_required(login_url='/login')
def fotos(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    menu = Menu.objects.all()
    current_user = request.user
    images = Images.objects.filter(user_id=current_user.id)
    context = {
        'setting':setting,
        'category': category,
        'menu': menu,
        'images': images,
    }
    return render(request, 'foto_paylasim.html', context)

@login_required(login_url='/login')
def imagedelete(request, id):
    current_user = request.user
    Images.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, ' Images deleted..')
    return HttpResponseRedirect('/user/fotos')
@login_required(login_url='/login')
def addimage(request):
    if request.method == 'POST':
        form = ImagesForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            data = Images()
            data.user_id = current_user.id
            data.title = form.cleaned_data['title']
            data.keywords = form.cleaned_data['title']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            data.category = form.cleaned_data['category']
            data.slug = form.cleaned_data['slug']
            data.detail = form.cleaned_data['detail']
            data.status = 'False'
            data.save()
            messages.success(request, 'Başarıyla işlem gerçekleşti')
            return HttpResponseRedirect('/user/fotos')
        else:
            messages.success(request, 'Content Form Error' + str(form.errors))
            return HttpResponseRedirect('/user/addimage')

    else:
        setting = Setting.objects.get(pk=1)
        category = Category.objects.all()
        menu = Menu.objects.all()
        form = ImagesForm()
        context = {
            'setting': setting,
            'menu': menu,
            'category': category,
            'form': form,
        }
        return render(request, 'foto_ekleme.html', context)

@login_required(login_url='/login')
def editimage(request, id):
    images = Images.objects.get(id=id)
    if request.method == 'POST':
        form = ImagesForm(request.POST, request.FILES, instance=images)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Images Updated Successfuly')
            return HttpResponseRedirect('/user/fotos')
        else:
            messages.success(request, 'Images Form Error:' + str(form.errors))
            return HttpResponseRedirect('/user/editimage' + str(id))
    else:
        setting = Setting.objects.get(pk=1)
        category = Category.objects.all()
        menu = Menu.objects.all()
        form = ImagesForm(instance=images)
        context = {
            'setting': setting,
            'menu': menu,
            'category': category,
            'form': form,

        }
        return render(request, 'foto_ekleme.html', context)

def addfotogalery(request,id):
    if request.method == 'POST':
        lasturl= request.META.get('HTTP_REFERER')
        form = FotoForm(request.POST, request.FILES)
        if form.is_valid():
            data = Foto()
            data.title = form.cleaned_data['title']
            data.images_id = id
            data.image = form.cleaned_data['image']
            data.save()
            messages.success(request, 'Your image has been successfully uploaded')
            return HttpResponseRedirect(lasturl)
        else:
            messages.warning(request, 'Form Error:' + str(form.errors))
            return HttpResponseRedirect(lasturl)

    else:
        contents = Images.objects.get(id=id)
        images = Foto.objects.filter(images_id=id)
        form = FotoForm()
        context = {
            'contents': contents,
            'images': images,
            'form': form,
        }
        return render(request, 'content_gallery.html', context)


@login_required(login_url='/login')
def contents(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    menu = Menu.objects.all()
    current_user = request.user
    contents = Content.objects.filter(user_id=current_user.id)
    context = {
        'setting': setting,
        'category': category,
        'menu': menu,
        'contents': contents,
    }
    return render(request, 'user_content.html', context)


@login_required(login_url='/login')
def addcontent(request):
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            data = Content()
            data.user_id = current_user.id
            data.menu = form.cleaned_data['menu']
            data.type = form.cleaned_data['type']
            data.title = form.cleaned_data['title']
            data.keywords = form.cleaned_data['keywords']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            data.category = form.cleaned_data['menu']
            data.slug = form.cleaned_data['slug']
            data.detail = form.cleaned_data['detail']
            data.status = 'False'
            data.save()
            messages.success(request, 'Başarıyla işlem gerçekleşti')
            return HttpResponseRedirect('/user/contents')
        else:
            messages.success(request, 'Content Form Error' + str(form.errors))
            return HttpResponseRedirect('/user/addcontent')

    else:
        setting = Setting.objects.get(pk=1)
        category = Category.objects.all()
        menu = Menu.objects.all()
        form = ContentForm()
        context = {
            'setting': setting,
            'menu': menu,
            'category': category,
            'form': form,
        }
        return render(request, 'user_addcontent.html', context)


@login_required(login_url='/login')
def contentedit(request, id):
    contents = Content.objects.get(id=id)
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES, instance=contents)
        if form.is_valid():
            form.save()

user/templates/change_password.html
{% extends "homebase.html" %}
{% block title %}{{ profile.user_name }} {% endblock %}
{% block keywords %}{{ setting.keywords }} {% endblock %}
{% block description %}{{ setting.description }}  {% endblock %}

{% block head %}<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />{% endblock %}
{% block sidebar %}
{% include "sidebar.html" %}
{% endblock %}


{% block content %}
<section id="subintro">
      <div class="container">
        <div class="row">
          <div class="span8">
            <ul class="breadcrumb">
              <li><a href="#"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
              <li><a href="/">Anasayfa</a><i class="icon-angle-right"></i></li>
              <li class="active">User Profile update</li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <section id="maincontent">
      <div class="container">
        <div class="row">
          <div class="span4">
            <aside>
              <div class="widget">
                   <div class="section-title">

            </div>
{% include "user_panel.html" %}
              </div>

            </aside>
          </div>
          <div class="span8">
            <div class="section-title">
                <h3 class="title">CHANGE PASSWORD</h3>
            </div>
            <div class="cart-table clearfix">
                    {% if messages %}
                    {% for message in messages %}
                        <div style="color: #d43f3a; font-size: medium ">
                            {{ message|safe }}
                        </div>
                    {% endfor %}
                {% endif %}

                <form method="post" >
                    {% csrf_token %}

                    {% for field in form %}
                    <p>
                        {{field.label_tag}}<br>
                        {{field}}
                        {%if filed.help_text %}
                        <small style="color: grey">{{filed.help_text}}</small>
                        {% endif %}
                        {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                    {% endfor %}
                    </p>
                    {%endfor%}
                    <div class="form-group">
                        <button class="btn btn_outline-info" type="submit">Save Changes</button>

                </div>
            <div class="spacer30">
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

user/templates/content_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News Gallery</title>
</head>
<body>
<h2>{{ contents.title }}</h2>
<hr>
{% if messages %}
    {% for messages in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ messages|safe }}
        </div>
    {% endfor %}
{% endif %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="id_title">Title:</label>
    <input type="text" name="title" class="input" placeholder="title" maxlength="50" id="id_title"></p>
    <label for="id_image">Image:</label>
    <input type="file" name="image" class="input" placeholder="image" accept="image/*" id="id_title"></p>
    <button class="btn-primary" type="submit">Upload Image</button>
</form>
<hr>


<h4>Yüklenen Resimler</h4>
{% for rs in images %}
    <img src="{{ rs.image.url }}" height="200">
{% endfor %}


</body>
</html>

user/templates/foto_ekleme.html
{% extends "homebase.html" %}

{% block title %} Add Content {{ setting.company }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}

    <link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}'/>

    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

{% endblock %}

{% block sidebar %}
    {% include "sidebar.html" %}
{% endblock %}


{% block content %}

    <section id="subintro">
        <script>
            function myFunction() {
                confirm("'Ürün silinecektir.Emin misniz?");
            }
        </script>
        <div class="container">
            <div class="row">
                <div class="span8">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
                        <li><a href="/">Anasayfa</a><i class="icon-angle-right"></i></li>
                        <li class="active">Foto Paylaşma</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section id="maincontent">
        <div class="container">
            <div class="row">
                <div class="span4">
                    <aside>
                        <div class="widget">
                            <div class="section-title">

                            </div>
                            {% include "user_panel.html" %}
                        </div>

                    </aside>
                </div>
                <div class="span8">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <div class="section-title">
                        <h3 class="title">Foto</h3>
                    </div>
                    <div class="cart-table clearfix">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                {{ form.media }}
                                {{ form.as_p }}
                            </fieldset>
                            <div class="form-group">
                                <button class="primary-btn" type="submit">SAVE</button>
                            </div>
                        </form>
                    </div>
                    <div class="spacer30">
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

user/templates/foto_paylasim.html
{% extends "homebase.html" %}
{% block title %}{{ profile.user_name }} COMMENTS {% endblock %}
{% block keywords %}{{ setting.keywords }} {% endblock %}
{% block description %}{{ setting.description }}  {% endblock %}

{% block head %}<link rel='shortcut icon' type='image/x-icon' href='{{ setting.icon.url }}' />{% endblock %}
{% block sidebar %}
    {% include "sidebar.html" %}
{% endblock %}


{% block content %}

    <section id="subintro">
        <script>
            function myFunction() {
                confirm("'Ürün silinecektir.Emin misniz?");
            }
        </script>
        <div class="container">
            <div class="row">
                <div class="span8">
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="icon-home"></i></a><i class="icon-angle-right"></i></li>
                        <li><a href="/">Anasayfa</a><i class="icon-angle-right"></i></li>
                        <li class="active">Content</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <section id="maincontent">
        <div class="container">
            <div class="row">
                <div class="span4">
                    <aside>
                        <div class="widget">
                            <div class="section-title">

                            </div>
                            {% include "user_panel.html" %}
                        </div>

                    </aside>
                </div>
                <div class="span8">
                    <div class="section-title">
                        <h3 class="title">User Information</h3>
                    </div>
                    <div class="cart-table clearfix">

                     <div class="section-title">
                        <h3 class="title">Foto paylaşım</h3>
                        <h4><a class="btn btn-success" href="/user/addimage">Add Image</a> </h4>
                    </div>
                    <table  class="fa-shopping-cart-table table">
                    {% load  static %}
                        <tr>
                            <th class="text-left">Image</th>
                            <th class="text-left">Title</th>
                            <th class="text-left">Category</th>
                            <th class="text-left">Detail</th>
                            <th class="text-left">Galery</th>

                            <th class="text-left">Created At</th>
                            <th class="text-left">Status</th>
                            <th class="text-left"></th>
                            <th class="text-left"></th>
                        </tr>
                        {% for rs in images %}
                        <tr>
                            <th class="text-left">
                                <a href="/images/{{ rs.id }}/{{ rs.slug }}">
                                <img src="{{ rs.image.url }}" style="height: 30px;"></a></th>
                            <th class="text-left"><a href="/images/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}</a></th>
                            <th class="text-left">{{ rs.category }}</th>
                            <th class="text-left">{{ rs.detail |safe |slice:20}}...</th>

                            <th class="text-left">
                                <a href="javascript:;" onclick="window.open('/user/addfotogalery/{{ rs.id }}','gallery','height=600,width=800,top=50,left=150')">
                                  <img src="{%   static '/images/gallery.jpg' %}" height="30">
                                </a>
                            </th>
                            <th class="text-left">{{ rs.create_at }}</th>
                            <th class="text-left">{{ rs.status }}</th>
                            <th class="text-left"><a class="btn btn-warning" href="/user/editimage/{{ rs.id }}">Edit </a></th>
                            <th class="text-left"><a onclick="return confirm('Will be Delete! Are you sure?')"class="btn btn-danger" href="/user/imagedelete/{{ rs.id }}">Delete</a> </th>
                        </tr>
                       {% endfor %}


                    </table>
                    <table  class="fa-shopping-cart-table table">
                    </table>
</div>
                    <div class="spacer30">
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

user/templates/news_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News Gallery</title>
</head>
<body>
<h2>{{ news.title }}</h2>
<hr>
{% if messages %}
    {% for messages in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ messages|safe }}
        </div>
    {% endfor %}
{% endif %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="news_id" id="id_news_id" value="{{ news.id }}">
    <label for="id_title">Title:</label>
    <input type="text" name="title" class="input" placeholder="title" maxlength="50" id="id_title"></p>
    <label for="id_image">Image:</label>
    <input type="file" name="image" class="input" placeholder="image" accept="image/*" id="id_title"></p>
    <button class="btn-primary" type="submit">Upload Image</button>
</form>
<hr>


<h4>Yüklenen Resimler</h4>
{% for rs in images %}
    <img src="{{ rs.image.url }}" height="200">
{% endfor %}


</body>
</html>

user/templates/user_panel.html
<div class="widget">
    <h4 class="rheading">User Panel<span></span></h4>
    <ul class="cat">
        <li><a href="/user">User Profile</a></li>
            <li><a href="/user/comments">My Comments</a></li>
            <li><a href="/user/fotos">My Foto</a></li>
            <li><a href="/user/contents">My Contents</a></li>
            <li><a href="/logout">Logout</a></li>
    </ul>
</div>